sudo: required
services:
  - docker

before_install:
  - docker build -t sbkohel/docker-react  -f  Dockerfile.dev .

script:
  - docker run sbkohel/docker-react npm run test -- --coverage

  deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "https://s3.console.aws.amazon.com/s3/buckets/elasticbeanstalk-us-east-2-585118949124/?region=us-east-2&tab=overview"
    bucket_path: "docker-react"
    on:
      branch: master
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key:
        secure: "$AWS_ACCESS_SECRET"